import { useEffect, useMemo, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { TopEntitiesBar } from "@/components/charts/TopEntitiesBar";
import { AfiaWordmark } from "@/components/brand/AfiaMark";
import { loadLibrarySummaries } from "@/lib/analytics-loader";
import {
  computeCooccurrenceLong,
  computeLibraryOverview,
  computeTopEntities,
  type AnalyzedDocSummary,
} from "@/lib/analytics-library";
import { Loader2, Printer, X } from "lucide-react";
import "@/styles/analytics-report.css";

const REPORT_DISCLAIMER =
  "Draft analytical summary — generated by AFIA local analysis. Requires professional review.";

function formatReportDate(): string {
  return new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function avgDocConfidence(doc: AnalyzedDocSummary): number {
  if (doc.entities.length === 0) return 0;
  const sum = doc.entities.reduce(
    (acc, entity) => acc + (entity.confidence ?? 0),
    0,
  );
  return sum / doc.entities.length;
}

function formatModel(model?: string): string {
  return model?.trim() || "—";
}

export default function AnalyticsReport() {
  const printedRef = useRef(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [docs, setDocs] = useState<AnalyzedDocSummary[]>([]);

  useEffect(() => {
    let active = true;
    void loadLibrarySummaries({
      onProgress: () => {},
    })
      .then((result) => {
        if (!active) return;
        setDocs(result.analyzed);
      })
      .catch((e) => {
        if (!active) return;
        setError(e instanceof Error ? e.message : "Failed to load library");
      })
      .finally(() => {
        if (active) setLoading(false);
      });
    return () => {
      active = false;
    };
  }, []);

  const overview = useMemo(() => computeLibraryOverview(docs), [docs]);
  const topEntities = useMemo(() => computeTopEntities(docs, 15), [docs]);
  const topCooccurrence = useMemo(
    () => computeCooccurrenceLong(docs).slice(0, 10),
    [docs],
  );
  const appendixRows = useMemo(
    () =>
      [...docs]
        .sort((a, b) => b.lastAccessedAt - a.lastAccessedAt)
        .map((doc) => ({
          id: doc.id,
          title: doc.filename,
          model: formatModel(doc.modelUsed),
          entityCount: doc.entities.length,
          avgConfidence: avgDocConfidence(doc),
        })),
    [docs],
  );

  useEffect(() => {
    if (loading || error || docs.length === 0 || printedRef.current) return;

    printedRef.current = true;
    const timer = window.setTimeout(() => {
      window.print();
    }, 600);

    return () => window.clearTimeout(timer);
  }, [loading, error, docs.length]);

  const handlePrint = () => {
    window.print();
  };

  const handleClose = () => {
    window.close();
  };

  if (loading) {
    return (
      <div className="analytics-report flex min-h-screen items-center justify-center gap-2 text-sm text-muted-foreground">
        <Loader2 className="size-4 animate-spin" />
        Preparing report…
      </div>
    );
  }

  if (error) {
    return (
      <div className="analytics-report flex min-h-screen flex-col items-center justify-center gap-3 p-6 text-center">
        <p className="text-sm text-destructive">{error}</p>
        <Button variant="outline" size="sm" onClick={handleClose}>
          Close
        </Button>
      </div>
    );
  }

  if (docs.length === 0) {
    return (
      <div className="analytics-report flex min-h-screen flex-col items-center justify-center gap-3 p-6 text-center">
        <p className="text-sm text-muted-foreground">
          No analyzed documents in your library yet.
        </p>
        <Button variant="outline" size="sm" onClick={handleClose}>
          Close
        </Button>
      </div>
    );
  }

  return (
    <div className="analytics-report">
      <div className="analytics-report__disclaimer">{REPORT_DISCLAIMER}</div>

      <div className="analytics-report__body">
        <section className="analytics-report__title-page">
          <AfiaWordmark className="text-2xl" />
          <h1>Analytics Summary Report</h1>
          <p className="text-sm text-muted-foreground">{formatReportDate()}</p>
          <p className="text-sm font-medium">
            {overview.documentCount} document
            {overview.documentCount === 1 ? "" : "s"} analyzed
          </p>
        </section>

        <section className="analytics-report__section">
          <h2>Overview</h2>
          <div className="analytics-report__stats">
            <div className="analytics-report__stat">
              <div className="analytics-report__stat-label">Documents</div>
              <div className="analytics-report__stat-value">
                {overview.documentCount}
              </div>
            </div>
            <div className="analytics-report__stat">
              <div className="analytics-report__stat-label">Total entities</div>
              <div className="analytics-report__stat-value">
                {overview.totalEntities.toLocaleString()}
              </div>
            </div>
            <div className="analytics-report__stat">
              <div className="analytics-report__stat-label">Avg confidence</div>
              <div className="analytics-report__stat-value">
                {(overview.avgConfidence * 100).toFixed(0)}%
              </div>
            </div>
            <div className="analytics-report__stat">
              <div className="analytics-report__stat-label">Top label</div>
              <div className="analytics-report__stat-value">
                {overview.topLabel ?? "—"}
              </div>
            </div>
          </div>
        </section>

        <section className="analytics-report__section">
          <h2>Top entities</h2>
          <p className="mb-3 text-xs text-muted-foreground">
            Most frequent entity texts across your library (top 15)
          </p>
          <TopEntitiesBar rows={topEntities} />
        </section>

        <section className="analytics-report__section">
          <h2>Top co-occurrences</h2>
          <p className="mb-3 text-xs text-muted-foreground">
            Entity pairs appearing in the same document (top 10)
          </p>
          {topCooccurrence.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No co-occurrence pairs found.
            </p>
          ) : (
            <table className="analytics-report__table">
              <thead>
                <tr>
                  <th>Entity A</th>
                  <th>Entity B</th>
                  <th>Count</th>
                </tr>
              </thead>
              <tbody>
                {topCooccurrence.map((row) => (
                  <tr key={`${row.entity_a}|${row.entity_b}`}>
                    <td>{row.entity_a}</td>
                    <td>{row.entity_b}</td>
                    <td className="num">{row.count}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </section>

        <section className="analytics-report__section analytics-report__section--appendix">
          <h2>Document appendix</h2>
          <p className="mb-3 text-xs text-muted-foreground">
            Per-document entity counts and average confidence
          </p>
          <table className="analytics-report__table">
            <thead>
              <tr>
                <th>Title</th>
                <th>Model</th>
                <th>Entities</th>
                <th>Avg confidence</th>
              </tr>
            </thead>
            <tbody>
              {appendixRows.map((row) => (
                <tr key={row.id}>
                  <td>{row.title}</td>
                  <td>{row.model}</td>
                  <td className="num">{row.entityCount}</td>
                  <td className="num">
                    {(row.avgConfidence * 100).toFixed(0)}%
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <p className="mt-8 text-xs text-muted-foreground">
          AFIA v1.0 · Generated locally from your decrypted library ·{" "}
          {new Date().toLocaleString()}
        </p>
      </div>

      <div className="analytics-report__toolbar">
        <Button variant="outline" size="sm" onClick={handleClose}>
          <X className="size-4" />
          Close
        </Button>
        <Button size="sm" onClick={handlePrint}>
          <Printer className="size-4" />
          Print / Save PDF
        </Button>
      </div>
    </div>
  );
}
